MOUSE_ENTER_OPACITY = 1
MOUSE_LEAVE_OPACITY = 0.2

ALWAYS_ON_TOP = True
APP_FONT = '16'

MARKED_DATE_COLOR = '#ff0000'
DEFAULT_DATE_COLOR = '#fff'

MARKED_DATE_LETTER_COLOR = '#fff'
DEFAULT_MARKED_DATE_LETTER_COLOR = '#000'

REMOVE_EVENT_AFTER_TIME_UP = True


DB_PATH = '~/reminder_desktop.db'

DEBUG = True

if DEBUG:
	MOUSE_ENTER_OPACITY = 1
	MOUSE_LEAVE_OPACITY = 1

	ALWAYS_ON_TOP = False

	DB_PATH = './reminder_desktop.db'
