from erdesktop.dialogs.about_dialog import AboutDialog
from erdesktop.dialogs.backup_dialog import BackupDialog
from erdesktop.dialogs.account_dialog import AccountDialog
from erdesktop.dialogs.settings_dialog import SettingsDialog
from erdesktop.dialogs.event_list_dialog import EventsListDialog
from erdesktop.dialogs.create_event_dialog import CreateEventDialog
